### ISSUE TITLE
Array of key-value-objects is converted into [object: Object] instead

### ISSUE THREAD

**Issue by j-frost** [BerryCloud/js-query-string-manipulator#1]
If I try out your example: 

```javascript
qsm('http://example.com/', {
  [URL_REMOVE]: ['test'],
  [URL_TOGGLE]: [
    {
      key: 'foo',
      value: 'bar',
    },
  ],
  [URL_SET]: [
    {
      key: 'xxx',
      value: '123',
    },
  ]
})
```
I get the result
> http://example.com/?0=%5Bobject%20Object%5D&0=%5Bobject%20Object%5D

instead of http://example.com/?foo=bar&xxx=123

**Comment by ReadyPlayerNaN** [comment]
Hello, @j-frost,

thank you for the feedback. I noticed that the example in the README was wrong. Using it with symbols should look the same as when using it without them.

So the example from README should now work. I added few tests to cover it. Does it work for you like this?

```javascript
import qsm, {
  URL_REMOVE, // Used for remove
  URL_SET, // Used for set
  URL_TOGGLE, // Used for toggle
} from 'query-string-manipulator';

qsm('http://example.com/', {
  [URL_REMOVE]: ['test'],
  [URL_TOGGLE]: {
    foo: 'bar',
  },
  [URL_SET]: {
    xxx: '123',
  },
})
```

**Comment by j-frost** [comment]
It does, but `getUrlParams` still returns it in the key-value-object form. If I want to manipulate the current URL, intuitively, I use that to get the current value, manipulate the result, and then pass it to `qsm`. Obviously that doesn't work. Am I meant to convert it back to proper objects myself?

**Comment by j-frost** [comment]
Clarifiying what I'd want to do: 

```javascript
const inputName = $(e.target).attr('name'),
  inputValue = $(e.target).val();
let queryParams = getUrlParams(window.location.href);
queryParams[inputName] = inputValue; // <-- this doesn't work
const qsmAction = (!inputValue)
  ? { [URL_REMOVE]: [inputName] }
  : { [URL_SET]: queryParams };
window.history.pushState('', '', qsm(window.location.pathname, qsmAction));
```

**Comment by ReadyPlayerNaN** [comment]
@j-frost, `getUrlParams` must return it as an array, because the URL may contain multiple parameters of the same name. 

In your example, you should not need to query URL params, because qsm does not change query params that it has no instruction of changing. Let me modify your example so it still

1. Reads the input name and value using jQuery,
2. Takes URL from window,
3. If input value is blank, removes the param from URL,
4. If input value is not blank, sets the URL param.

```javascript
const inputName = $(e.target).attr('name');
const inputValue = $(e.target).val();
const qsmAction = (!inputValue ?
  { [URL_REMOVE]: [inputName] } : { [URL_SET]: { [inputName]: inputValue });
window.history.pushState('', '', qsm(window.location.href, qsmAction));
```

**Comment by j-frost** [comment]
Ah ok. I didn't even try that because I assumed because of the wording that `URL_SET` would set the entire string. My bad.

**Comment by j-frost** [comment]
Thank you for your help, @just-paja :)

**Comment by ReadyPlayerNaN** [comment]
You're welcome, @j-frost :-)
