### ISSUE TITLE
Query params with square brackets misbehave

### ISSUE THREAD

**Issue by j-frost** [BerryCloud/js-query-string-manipulator#2]
When setting a query param that has to be URI encoded because its key contains square brackets for the second time, the result is not as expected. 

So for instance, let's say I want to set the key `f[numPages][v][min]` to the value of `1`. I can `qsm(window.location.href, {[URL_SET]: { "f[numPages][v][min]": 1 }})` no problem. I get as resulting URL `https://example.org?f%5BnumPages%5D%5Bv%5D%5Bmin%5D=1`.

But if the value now changes, and I need to set it again, when I call `qsm(window.location.href, {[URL_SET]: { "f[numPages][v][min]": 2 }})` I now get `https://example.org?f%255BnumPages%255D%255Bv%255D%255Bmin%255D=1&f%5BnumPages%5D%5Bv%5D%5Bmin%5D=2` instead of what I'd expect, which is `https://example.org?f%5BnumPages%5D%5Bv%5D%5Bmin%5D=2`.

**Comment by ReadyPlayerNaN** [comment]
Interesting, could be an issue with url decode. Seems that qsm does not expect URL encoded address.

Accepting URL encoded addresses might be a useful feature.

**Comment by ReadyPlayerNaN** [comment]
@j-frost, do you have more examples of non-working encoded URLs?

**Comment by j-frost** [comment]
I don't have any "real life" examples, so to speak -- I just wanted to pass an array via GET parameters, so that's how I found out about this. I did try `{` though, and they're also doubly encoded by the end.

**Comment by j-frost** [comment]
For now, I can just `decodeURIComponent` the `window.location.href` -- but I think it's not super safe to just do so blindly, right? Maybe qsm can take on this responsibility.

**Comment by ReadyPlayerNaN** [comment]
@j-frost, could you please try current master version if it works for you?

**Comment by j-frost** [comment]
@just-paja I got 4 passing out of 4 and it seems to do what I want in production as well! :)

**Comment by ReadyPlayerNaN** [comment]
Cool. I released it to npm. Thank you for your feedback, @j-frost. I'm sure it will get useful in the future.
